version: "3"

services:
  bookdee_server:
    image: aryanyad01/bookdee_server:v1
    build:
      context: "."
      dockerfile: Dockerfile.server
    restart: unless-stopped
    ports:
      - "7890:80"
    networks:
      - net1-backend

  bookdee_backend:
    image: aryanyad01/bookdee_backend:v2
    networks:
      - net1-backend
    volumes :
      - type: volume
        source: bookdee_backend_vol
        target: /mnt/
    build:
      context: "."
      dockerfile: Dockerfile.backend
    restart: unless-stopped

volumes:
   bookdee_backend_vol:
    external : true

networks:
  net1-backend:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
